//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3603
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Elegant.Ui.CommandSourceAttribute("Operationen.ApplicationCommands", "Operationen.ApplicationCommands")]

namespace Operationen
{
    //  This class is required for commands suppport.
// Do not modify this code inside the editor.

public class ApplicationCommands
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command DateiTypenView = new Elegant.Ui.Command("DateiTypenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command DateienView = new Elegant.Ui.Command("DateienView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command RichtlinienView = new Elegant.Ui.Command("RichtlinienView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenKatalogView = new Elegant.Ui.Command("OperationenKatalogView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command DokumenteView = new Elegant.Ui.Command("DokumenteView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command GebieteView = new Elegant.Ui.Command("GebieteView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command Exit = new Elegant.Ui.Command("Exit");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OptionsView = new Elegant.Ui.Command("OptionsView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command PrintIstOperationen = new Elegant.Ui.Command("PrintIstOperationen");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgenFunktionenView = new Elegant.Ui.Command("ChirurgenFunktionenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command NotizTypenView = new Elegant.Ui.Command("NotizTypenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command AkademischeAusbildungTypenView = new Elegant.Ui.Command("AkademischeAusbildungTypenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command AbteilungenView = new Elegant.Ui.Command("AbteilungenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command AbteilungenChirurgenView = new Elegant.Ui.Command("AbteilungenChirurgenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command WeiterbilderChirurgenView = new Elegant.Ui.Command("WeiterbilderChirurgenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgNew = new Elegant.Ui.Command("ChirurgNew");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgEdit = new Elegant.Ui.Command("ChirurgEdit");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgDelete = new Elegant.Ui.Command("ChirurgDelete");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command BaekWbOrdnung = new Elegant.Ui.Command("BaekWbOrdnung");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command BaekWbRichtlinien = new Elegant.Ui.Command("BaekWbRichtlinien");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenEditView = new Elegant.Ui.Command("OperationenEditView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command KommentareView = new Elegant.Ui.Command("KommentareView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command NotizenView = new Elegant.Ui.Command("NotizenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command AkademischeAusbildungView = new Elegant.Ui.Command("AkademischeAusbildungView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command PlanOperationenView = new Elegant.Ui.Command("PlanOperationenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgDokumenteView = new Elegant.Ui.Command("ChirurgDokumenteView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command RichtlinienOpsKodeUnassignedView = new Elegant.Ui.Command("RichtlinienOpsKodeUnassignedView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgenRichtlinienView = new Elegant.Ui.Command("ChirurgenRichtlinienView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenView = new Elegant.Ui.Command("OperationenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenZeitenVergleichView = new Elegant.Ui.Command("OperationenZeitenVergleichView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OPDauerFortschrittView = new Elegant.Ui.Command("OPDauerFortschrittView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ChirurgOperationenView = new Elegant.Ui.Command("ChirurgOperationenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command GesamtOperationenView = new Elegant.Ui.Command("GesamtOperationenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenVergleichView = new Elegant.Ui.Command("OperationenVergleichView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command PlanOperationVergleichIstView = new Elegant.Ui.Command("PlanOperationVergleichIstView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command PlanOperationVergleichView = new Elegant.Ui.Command("PlanOperationVergleichView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command RichtlinienVergleichView = new Elegant.Ui.Command("RichtlinienVergleichView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command RichtlinienVergleichOverviewView = new Elegant.Ui.Command("RichtlinienVergleichOverviewView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command KlinischeErgebnisseView = new Elegant.Ui.Command("KlinischeErgebnisseView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command UserChangePasswordView = new Elegant.Ui.Command("UserChangePasswordView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command UserSetPasswordView = new Elegant.Ui.Command("UserSetPasswordView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command LogView = new Elegant.Ui.Command("LogView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command SerialNumbersView = new Elegant.Ui.Command("SerialNumbersView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command UpdateFromFolder = new Elegant.Ui.Command("UpdateFromFolder");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command SerialBuy = new Elegant.Ui.Command("SerialBuy");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command InstallLicenseWizard = new Elegant.Ui.Command("InstallLicenseWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command UpdateFromWww = new Elegant.Ui.Command("UpdateFromWww");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command CopyWWWProgramUpdateFilesView = new Elegant.Ui.Command("CopyWWWProgramUpdateFilesView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command SecGroupsView = new Elegant.Ui.Command("SecGroupsView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command SecGroupsChirurgenView = new Elegant.Ui.Command("SecGroupsChirurgenView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command SecGroupsSecRightsView = new Elegant.Ui.Command("SecGroupsSecRightsView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command SecUserOverviewView = new Elegant.Ui.Command("SecUserOverviewView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command LangDeDe = new Elegant.Ui.Command("LangDeDe");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command LangEnUs = new Elegant.Ui.Command("LangEnUs");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ImportChirurgenExcludeView = new Elegant.Ui.Command("ImportChirurgenExcludeView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenImportView = new Elegant.Ui.Command("OperationenImportView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ExecAutoImport = new Elegant.Ui.Command("ExecAutoImport");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ImportRichtlinienWizard = new Elegant.Ui.Command("ImportRichtlinienWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ImportRichtlinienZuordnungWizard = new Elegant.Ui.Command("ImportRichtlinienZuordnungWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ImportChirurgWizard = new Elegant.Ui.Command("ImportChirurgWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ImportOperationenMobileWizard = new Elegant.Ui.Command("ImportOperationenMobileWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ImportOPSWizard = new Elegant.Ui.Command("ImportOPSWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ExportRichtlinienWizard = new Elegant.Ui.Command("ExportRichtlinienWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ExportRichtlinienZuordnungWizard = new Elegant.Ui.Command("ExportRichtlinienZuordnungWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ExportChirurgWizard = new Elegant.Ui.Command("ExportChirurgWizard");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ExportOperationenKatalogView = new Elegant.Ui.Command("ExportOperationenKatalogView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command HelpChm = new Elegant.Ui.Command("HelpChm");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command WwwHelp = new Elegant.Ui.Command("WwwHelp");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command WwwHome = new Elegant.Ui.Command("WwwHome");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command AboutBox = new Elegant.Ui.Command("AboutBox");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command DebugSql = new Elegant.Ui.Command("DebugSql");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command DebugExportOperationen = new Elegant.Ui.Command("DebugExportOperationen");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command UpdateSerialnumbersView = new Elegant.Ui.Command("UpdateSerialnumbersView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command DebugReloadUserRights = new Elegant.Ui.Command("DebugReloadUserRights");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command OperationenSummaryView = new Elegant.Ui.Command("OperationenSummaryView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command EigeneDateien = new Elegant.Ui.Command("EigeneDateien");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ribbon = new Elegant.Ui.Command("ribbon");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command RichtlinienSollIstView = new Elegant.Ui.Command("RichtlinienSollIstView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ClientServerView = new Elegant.Ui.Command("ClientServerView");
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
    public static Elegant.Ui.Command ZeitraeumeView = new Elegant.Ui.Command("ZeitraeumeView");
}
}
