//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Operationen.de.op_log.www {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OperationenWebServiceSoap", Namespace="http://www.op-log.de/")]
    public partial class OperationenWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterLicenseOneWayOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterLicenseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OperationenWebService() {
            this.Url = global::Operationen.Properties.Settings.Default.Operationen_de_op_log_www_OperationenWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterLicenseOneWayCompletedEventHandler RegisterLicenseOneWayCompleted;
        
        /// <remarks/>
        public event RegisterLicenseCompletedEventHandler RegisterLicenseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.op-log.de/RegisterLicenseOneWay", RequestNamespace="http://www.op-log.de/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegisterLicenseOneWay(string data) {
            this.Invoke("RegisterLicenseOneWay", new object[] {
                        data});
        }
        
        /// <remarks/>
        public void RegisterLicenseOneWayAsync(string data) {
            this.RegisterLicenseOneWayAsync(data, null);
        }
        
        /// <remarks/>
        public void RegisterLicenseOneWayAsync(string data, object userState) {
            if ((this.RegisterLicenseOneWayOperationCompleted == null)) {
                this.RegisterLicenseOneWayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterLicenseOneWayOperationCompleted);
            }
            this.InvokeAsync("RegisterLicenseOneWay", new object[] {
                        data}, this.RegisterLicenseOneWayOperationCompleted, userState);
        }
        
        private void OnRegisterLicenseOneWayOperationCompleted(object arg) {
            if ((this.RegisterLicenseOneWayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterLicenseOneWayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.op-log.de/RegisterLicense", RequestNamespace="http://www.op-log.de/", ResponseNamespace="http://www.op-log.de/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterLicense(string data, out string errorText) {
            object[] results = this.Invoke("RegisterLicense", new object[] {
                        data});
            errorText = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterLicenseAsync(string data) {
            this.RegisterLicenseAsync(data, null);
        }
        
        /// <remarks/>
        public void RegisterLicenseAsync(string data, object userState) {
            if ((this.RegisterLicenseOperationCompleted == null)) {
                this.RegisterLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterLicenseOperationCompleted);
            }
            this.InvokeAsync("RegisterLicense", new object[] {
                        data}, this.RegisterLicenseOperationCompleted, userState);
        }
        
        private void OnRegisterLicenseOperationCompleted(object arg) {
            if ((this.RegisterLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterLicenseCompleted(this, new RegisterLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RegisterLicenseOneWayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RegisterLicenseCompletedEventHandler(object sender, RegisterLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591